/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
  export interface GlobalComponents {
    AdminHeader: typeof import("./src/components/admin/AdminHeader.vue")["default"];
    AdminLayout: typeof import("./src/components/admin/AdminLayout.vue")["default"];
    AdminSidebar: typeof import("./src/components/admin/AdminSidebar.vue")["default"];
    ArticleMeta: typeof import("./src/components/common/ArticleMeta.vue")["default"];
    AvatarCropper: typeof import("./src/components/common/AvatarCropper.vue")["default"];
    BackToTop: typeof import("./src/components/BackToTop.vue")["default"];
    BannerSection: typeof import("./src/components/home/BannerSection.vue")["default"];
    BlockHeader: typeof import("./src/components/common/BlockHeader.vue")["default"];
    BreadcrumbNav: typeof import("./src/components/common/BreadcrumbNav.vue")["default"];
    CommunitySection: typeof import("./src/components/home/CommunitySection.vue")["default"];
    ElAlert: typeof import("element-plus/es")["ElAlert"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCarousel: typeof import("element-plus/es")["ElCarousel"];
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElEmpty: typeof import("element-plus/es")["ElEmpty"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSkeleton: typeof import("element-plus/es")["ElSkeleton"];
    ElSlider: typeof import("element-plus/es")["ElSlider"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTimeline: typeof import("element-plus/es")["ElTimeline"];
    ElTimelineItem: typeof import("element-plus/es")["ElTimelineItem"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    ErrorBoundary: typeof import("./src/components/common/ErrorBoundary.vue")["default"];
    FooterLinks: typeof import("./src/components/FooterLinks.vue")["default"];
    HasPermission: typeof import("./src/components/common/HasPermission.vue")["default"];
    Header: typeof import("./src/components/Header.vue")["default"];
    InfoSection: typeof import("./src/components/home/InfoSection.vue")["default"];
    NewsListItem: typeof import("./src/components/common/NewsListItem.vue")["default"];
    NewsSection: typeof import("./src/components/home/NewsSection.vue")["default"];
    PageLayout: typeof import("./src/components/common/PageLayout.vue")["default"];
    QuillEditor: typeof import("./src/components/common/QuillEditor.vue")["default"];
    RelatedList: typeof import("./src/components/common/RelatedList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SectionHeader: typeof import("./src/components/common/SectionHeader.vue")["default"];
    TeachersSection: typeof import("./src/components/home/TeachersSection.vue")["default"];
    VideoPlayer: typeof import("./src/components/VideoPlayer.vue")["default"];
    VideoSection: typeof import("./src/components/home/VideoSection.vue")["default"];
  }
}
